### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [dmidk/Open-Data-QGIS-plugin#45]
#Problem

Please adjust the link for the plugin homepage in metadata.txt to reference the repo as your link is more generic

**Comment by petergarnaes** [comment]
@NyakudyaA Is linking to the Github repository sufficient? We do not have a separate homepage the the plugin specifically

**Comment by NyakudyaA** [comment]
linking to the github is sufficient. your homepage is too generic and doesn't only show plugin info

**Comment by petergarnaes** [comment]
Thanks for your feedback 👍🏻
