### ISSUE TITLE
Cannot install plug-in in fresh qgis install 

### ISSUE THREAD

**Issue by knas4ever** [dmidk/Open-Data-QGIS-plugin#50]
I get this error when I try to install the phugin (in windows):

Couldn't load plugin 'OMI Open Data due to an error when calling its classFactory() method

ImportError: cannot import name 'json_normalize' from 'pandas.io.json' (C: \PROGRA~1\QGIS32~1.8\apps\Python39\lib\site-packages\pandas \io\json\__init__.py)

**Comment by petergarnaes** [comment]
Hello @knas4ever, thanks for reporting. We _just_ released a new version with a fix for QGIS version 3.28, is that the version of QGIS you are using? If so, please try out the new version of the plugin (1.0.5) and see if it fixes the problem. 

If it does, please let us know

**Comment by knas4ever** [comment]
Ahhh now it works 🙂 omg I was trying everything with trying to install
pandas and pulling my hair out. 🤣 Nov it just works! Thanks a lot. Now I
can let my hair grow again 😉

Best regards
Claus Elholm

tor. 13. jul. 2023 13.23 skrev Peter Garnæs ***@***.***>:

**Comment by knas4ever** [comment]
By the way. Is there any way to correct the time to CET?

Seems the data is +4 hours.

Thanks

/Claus

fre. 14. jul. 2023 07.25 skrev Claus Elholm ***@***.***>:

**Comment by petergarnaes** [comment]
Closing this issue, as the original issue is solved.

@knas4ever The +4 hour problem is nothing we are able to reproduce, unless you give us a more detailed explanation of your problem. Maybe your computers timezone is set to +4 hours?
